//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisPeriodMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalysisPeriodMaster()
        {
            this.NYSPFPDatas = new HashSet<NYSPFPData>();
        }
    
        public int APM_Id { get; set; }
        public string APM_Period { get; set; }
        public bool APM_Active { get; set; }
        public string APM_CreatedBy { get; set; }
        public System.DateTime APM_CreatedOn { get; set; }
        public string APM_UpdatedBy { get; set; }
        public System.DateTime APM_UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NYSPFPData> NYSPFPDatas { get; set; }
    }
}
