//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalendarMaster()
        {
            this.NYSPFPDatas = new HashSet<NYSPFPData>();
        }
    
        public int CAL_Id { get; set; }
        public int CAL_Year { get; set; }
        public int CAL_Month { get; set; }
        public string CAL_MonthText { get; set; }
        public bool CAL_Active { get; set; }
        public int CAL_OrderBy { get; set; }
        public string CAL_CreatedBy { get; set; }
        public System.DateTime CAL_CreatedOn { get; set; }
        public string CAL_UpdatedBy { get; set; }
        public System.DateTime CAL_UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NYSPFPData> NYSPFPDatas { get; set; }
    }
}
