//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTypeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTypeMaster()
        {
            this.EventMeasureMasters = new HashSet<EventMeasureMaster>();
        }
    
        public int EVM_Id { get; set; }
        public string EVM_EventType { get; set; }
        public bool EVM_Active { get; set; }
        public string EVM_CreatedBy { get; set; }
        public System.DateTime EVM_CreatedOn { get; set; }
        public string EVM_UpdatedBy { get; set; }
        public System.DateTime EVM_UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventMeasureMaster> EventMeasureMasters { get; set; }
    }
}
