//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMeasureMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventMeasureMaster()
        {
            this.NYSPFPDatas = new HashSet<NYSPFPData>();
        }
    
        public int EMM_Id { get; set; }
        public int EMM_MEM_Id { get; set; }
        public int EMM_EVM_Id { get; set; }
        public string EMM_TimePeriod { get; set; }
        public bool EMM_Active { get; set; }
        public bool EMM_DisplayInApp { get; set; }
        public string EMM_CreatedBy { get; set; }
        public System.DateTime EMM_CreatedOn { get; set; }
        public string EMM_UpdatedBy { get; set; }
        public System.DateTime EMM_UpdatedOn { get; set; }
    
        public virtual EventTypeMaster EventTypeMaster { get; set; }
        public virtual MeasureMaster MeasureMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NYSPFPData> NYSPFPDatas { get; set; }
    }
}
