//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeasureMaster()
        {
            this.EventMeasureMasters = new HashSet<EventMeasureMaster>();
        }
    
        public int MEM_Id { get; set; }
        public string MEM_Measure { get; set; }
        public int MEM_Multiplier { get; set; }
        public bool MEM_Active { get; set; }
        public string MEM_CreatedBy { get; set; }
        public System.DateTime MEM_CreatedOn { get; set; }
        public string MEM_UpdatedBy { get; set; }
        public System.DateTime MEM_UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventMeasureMaster> EventMeasureMasters { get; set; }
    }
}
