//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NYSPFPData
    {
        public int NPD_Id { get; set; }
        public int NPD_HOS_Id { get; set; }
        public int NPD_Cal_Id { get; set; }
        public int NPD_EMM_Id { get; set; }
        public decimal NPD_Numerator { get; set; }
        public decimal NPD_Denominator { get; set; }
        public decimal NPD_Measurement { get; set; }
        public Nullable<int> NPD_APM_Id { get; set; }
        public string NPD_SourceType { get; set; }
        public string NPD_CreatedBy { get; set; }
        public System.DateTime NPD_CreatedOn { get; set; }
        public string NPD_UpdatedBy { get; set; }
        public System.DateTime NPD_UpdatedOn { get; set; }
    
        public virtual AnalysisPeriodMaster AnalysisPeriodMaster { get; set; }
        public virtual CalendarMaster CalendarMaster { get; set; }
        public virtual EventMeasureMaster EventMeasureMaster { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
