//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFPEntities : DbContext
    {
        public PFPEntities()
            : base("name=PFPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisPeriodMaster> AnalysisPeriodMasters { get; set; }
        public virtual DbSet<CalendarMaster> CalendarMasters { get; set; }
        public virtual DbSet<EventMeasureMaster> EventMeasureMasters { get; set; }
        public virtual DbSet<EventTypeMaster> EventTypeMasters { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<MeasureMaster> MeasureMasters { get; set; }
        public virtual DbSet<NYSPFPData> NYSPFPDatas { get; set; }
        public virtual DbSet<RolesMaster> RolesMasters { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
