//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMaster
    {
        public int ROM_Id { get; set; }
        public string ROM_Name { get; set; }
        public string ROM_Description { get; set; }
        public bool ROM_Active { get; set; }
        public string ROM_CreatedBy { get; set; }
        public System.DateTime ROM_CreatedOn { get; set; }
        public string ROM_UpdatedBy { get; set; }
        public System.DateTime ROM_UpdatedOn { get; set; }
        public Nullable<bool> ROM_IsDeleted { get; set; }
    }
}
