//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int URS_Id { get; set; }
        public int URS_UserId { get; set; }
        public int URS_RoleId { get; set; }
        public string URS_CreatedBy { get; set; }
        public Nullable<System.DateTime> URS_CreatedOn { get; set; }
        public string URS_UpdatedBy { get; set; }
        public Nullable<System.DateTime> URS_UpdatedOn { get; set; }
        public bool? URS_Active { get; set; }
    }
}
