-- =============================================
-- Author:		<vijayanth Sandhi>
-- Create date: <1/13/2020>
-- Description:	<spPressureInjuryRates>
-- =============================================
--	[pfp].[spPressureInjuryRates] @fromyear = 2017, @toyear = 2017, @orgid = 5069, @type = 2
CREATE PROCEDURE [pfp].[spPressureInjuryRates]
	@fromyear int = 0,
	@toyear int = 0,
	@orgid int = 0,
	@type int = 0
AS
BEGIN

	IF(@TYPE > 0)
	BEGIN
		DECLARE @MEASURE INT = 0, @EVENT INT = 0, @TIMEPERIOD VARCHAR(50) = '', @HOS_PFI int = 0
		SELECT @MEASURE = EMM_MEM_ID, @EVENT=EMM_EVM_ID, @TIMEPERIOD = EMM_TIMEPERIOD FROM PFP.EVENTMEASUREMASTER WHERE EMM_EVM_ID=@TYPE;
		SELECT @HOS_PFI = HOS_PFI FROM PFP.HOSPITALS WHERE HOS_ID=@ORGID;

	END

		SELECT [CAL_YEAR] [YEAR] ,[CAL_MONTH] [MONTH],[CAL_MONTHTEXT] [MONTHTEXT],[HOS_PFI] ,[HOS_HOSPITALNAME] ,[NPD_APM_ID] ,[EMM_TIMEPERIOD],[NPD_EMM_ID]
			,[NPD_NUMERATOR] [NUMERATOR],[NPD_DENOMINATOR] [DENOMINATOR],[NPD_MEASUREMENT],MEM.MEM_MULTIPLIER [MULTIPLIER]
			,CASE WHEN [CAL_MONTH] IN (1,2,3) THEN 1 WHEN [CAL_MONTH] IN (4,5,6) THEN 2 WHEN [CAL_MONTH] IN (7,8,9) THEN 3 WHEN [CAL_MONTH] IN (10,11,12) THEN 4 END AS QUART
		INTO #TEMP1HIIN_MEASURES 
		FROM [PFP].[PFP].[NYSPFPDATA] NPD JOIN [PFP].[PFP].[CALENDARMASTER] CM ON NPD.[NPD_CAL_ID] = CM.[CAL_ID] AND [CAL_ACTIVE] = 1
		JOIN [PFP].[PFP].[HOSPITALS] HS ON NPD.[NPD_HOS_ID] = HOS_Id AND [HOS_ACTIVE] = 1
		JOIN [PFP].[PFP].[EVENTMEASUREMASTER] EMM ON EMM.[EMM_Id] = NPD.[NPD_EMM_ID] AND [EMM_ACTIVE] = 1
		JOIN [PFP].[PFP].[MEASUREMASTER] MEM ON MEM.[MEM_ID] = EMM.[EMM_MEM_ID] AND [MEM_ACTIVE] = 1
		WHERE MEM.[MEM_ID] = @MEASURE AND EMM_EVM_ID = @EVENT 
		AND [CAL_YEAR] BETWEEN @FROMYEAR AND @TOYEAR
	  

		IF(@TIMEPERIOD = 'Quarterly')
		BEGIN
			SELECT [YEAR], QUART AS [MONTH],'Q' + CAST(QUART AS VARCHAR) MONTHTEXT,
				ISNULL((SELECT SUM(CAST(NUMERATOR AS DECIMAL(24,9))) FROM #TEMP1HIIN_MEASURES PFP WHERE HOS_PFI =  @HOS_PFI AND PFP.[QUART] = PFPH.[QUART] AND PFP.[YEAR] = PFPH.[YEAR]),0) NUMERATOR,
					ISNULL((SELECT SUM(CAST(DENOMINATOR AS DECIMAL(24,9))) FROM #TEMP1HIIN_MEASURES PFP WHERE HOS_PFI =  @HOS_PFI AND PFP.[QUART] = PFPH.[QUART] AND PFP.[YEAR] = PFPH.[YEAR]),0) DENOMINATOR,
				CASE WHEN ISNULL(SUM(CAST(DENOMINATOR AS DECIMAL(24,9))),0) = 0 THEN 0 ELSE ISNULL((SELECT  SUM(CAST(PFP.NUMERATOR AS DECIMAL(24,9)))/SUM(CAST(PFP.DENOMINATOR AS DECIMAL(24,9)))*[MULTIPLIER]
				FROM #TEMP1HIIN_MEASURES PFP 
				WHERE  HOS_PFI =  @HOS_PFI AND PFP.[YEAR] = PFPH.[YEAR] AND PFP.QUART = PFPH.QUART
				GROUP BY PFP.[YEAR], PFP.QUART, [MULTIPLIER] ),0) END HOSPRATE,
			CASE WHEN ISNULL(SUM(CAST(DENOMINATOR AS DECIMAL(24,9))),0) = 0 THEN 0 ELSE ISNULL((SUM(CAST(NUMERATOR AS DECIMAL(24,9)))/SUM(CAST(DENOMINATOR AS DECIMAL(24,9)))*[MULTIPLIER]),0) END AS PFPRATE, COUNT(HOS_PFI) HOSCOUNT 
			FROM  #TEMP1HIIN_MEASURES PFPH
			GROUP BY [YEAR], QUART,[MULTIPLIER]
			ORDER BY [YEAR], QUART;
		END
		ELSE BEGIN
			SELECT [YEAR], 
					[MONTH], 
					[MONTHTEXT], 
					ISNULL((SELECT SUM(CAST(NUMERATOR AS DECIMAL(24,9))) FROM #TEMP1HIIN_MEASURES PFP WHERE HOS_PFI =  @HOS_PFI AND PFP.[MONTH] = PFPH.[MONTH] AND PFP.[YEAR] = PFPH.[YEAR]),0) NUMERATOR,
					ISNULL((SELECT SUM(CAST(DENOMINATOR AS DECIMAL(24,9))) FROM #TEMP1HIIN_MEASURES PFP WHERE HOS_PFI =  @HOS_PFI AND PFP.[MONTH] = PFPH.[MONTH] AND PFP.[YEAR] = PFPH.[YEAR]),0) DENOMINATOR,
					CASE WHEN ISNULL(SUM(CAST(DENOMINATOR AS DECIMAL(24,9))),0) = 0 THEN 0 ELSE ISNULL((SELECT  SUM(CAST(PFP.NUMERATOR AS DECIMAL(24,9)))/SUM(CAST(PFP.DENOMINATOR AS DECIMAL(24,9)))*[MULTIPLIER]
						FROM #TEMP1HIIN_MEASURES PFP 
						WHERE  HOS_PFI =  @HOS_PFI AND PFP.[MONTH] = PFPH.[MONTH] AND PFP.[YEAR] = PFPH.[YEAR]
						GROUP BY PFP.[YEAR], PFP.[MONTH], [MULTIPLIER]),0) END HOSPRATE,
				CASE WHEN ISNULL(SUM(CAST(DENOMINATOR AS DECIMAL(24,9))),0) = 0 THEN 0 ELSE ISNULL((SUM(CAST(NUMERATOR AS DECIMAL(24,9)))/SUM(CAST(DENOMINATOR AS DECIMAL(24,9)))*[MULTIPLIER]),0) END AS PFPRATE, 
				COUNT(HOS_PFI) HOSCOUNT 
			FROM  #TEMP1HIIN_MEASURES PFPH
			GROUP BY [YEAR], [MONTH],[MONTHTEXT],[MULTIPLIER]
			ORDER BY [YEAR], [MONTH];
		END

		--DROP TABLE #TEMP1HIIN_MEASURES

END
